version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "."
    schedule:
      interval: "daily"
      time: "16:29"
  - package-ecosystem: "github-actions"
    directory: ".github/workflows/"
    schedule:
      interval: "daily"
      time: "16:33"
